version: "3.9"

services:
  backend:
    image: philipid3s/kargo-backend
    container_name: kargo-backend
    ports:
      - "8000:8000"
    environment:
      - KARGO_DATABASE_URL=sqlite:////app/data/kargo.db
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    image: philipid3s/kargo-frontend
    container_name: kargo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
